buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    plugins.withId("com.android.library") {
        if (project.android.namespace == null) {
            def manifest = project.file("src/main/AndroidManifest.xml")
            if (manifest.exists()) {
                def pkg = new XmlParser().parse(manifest).attribute('package')
                if (pkg != null) {
                    project.android.namespace = pkg
                }
            }
            if (project.android.namespace == null) {
                project.android.namespace = project.group ?: "com.pos.${project.name}"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
